<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Quartz.AspNetCore" />
    <PackageReference Include="Quartz.HttpClient" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Libraries/QuartzSupervisor.Dashboard/QuartzSupervisor.Dashboard.csproj" />
    <ProjectReference Include="../../Libraries/QuartzSupervisor.Integration/QuartzSupervisor.Integration.csproj" />
  </ItemGroup>
</Project>
